sudo: required
services:
  - docker
before_install:
  - docker build -t pciaco/apptalk:latest ./apptalk
script:
  - docker images pciaco/apptalk
after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pciaco/apptalk